services:
  # Auth Service MySQL Database
  auth-mysql:
    image: mysql:8.0
    container_name: auth-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - auth_mysql_data:/var/lib/mysql
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 30s

  # User Service MySQL Database
  user-mysql:
    image: mysql:8.0
    container_name: user-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USER_DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"  # Different port to avoid conflicts
    volumes:
      - user_mysql_data:/var/lib/mysql
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 30s

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: microservice-auth
    env_file:
      - .env
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - GIN_MODE=${GIN_MODE}
      - DB_HOST=auth-mysql
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${AUTH_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY_HOURS=${JWT_EXPIRY_HOURS}
      - USER_SERVICE_URL=user-service:9081
    ports:
      - "8080:8080"
    volumes:
      - ./auth-service:/app/auth-service
      - ./shared:/app/shared
    depends_on:
      auth-mysql:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped

  # User Service
  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: microservice-user
    env_file:
      - .env
    environment:
      - PORT=${USER_SERVICE_PORT}
      - GIN_MODE=${GIN_MODE}
      - DB_HOST=user-mysql
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${USER_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_SERVICE_URL=http://auth-service:8080
    ports:
      - "8081:8081"
      - "9081:9081"
    volumes:
      - ./user-service:/app/user-service
      - ./shared:/app/shared
    depends_on:
      user-mysql:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped

networks:
  microservice-network:
    driver: bridge

volumes:
  auth_mysql_data:
    driver: local
  user_mysql_data:
    driver: local 