root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "tmp/main"
  full_bin = ""
  watch_dir = ""
  watch_ext = "go"
  ignore_dir = ["assets", "tmp", "vendor"]

[log]
  level = "info"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = false 